main:
  project_name: BankCampaignAI 
  experiment_name: development
  steps: all
etl:
  sample: "dataset.csv"
data_check:
  kl_threshold: 0.2
modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "y" 
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1                # Here -1 means all available cores
    criterion: log_loss
    max_features: 0.33
    oob_score: true           # DO not change the following
    